networks:
  bot-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
services:
  nonebot:
    build:
      context: ./nonebot
      dockerfile: dockerfile
    volumes:
      - /opt/bot-data/.env.prod:/app/.env.prod
      - /opt/bot-data/plugin_data:/app/plugin_data
    environment:
      ENVIRONMENT: prod
    networks:
      - bot-network
    restart: always
